apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    team: galera-tec
    env: production
    severity: critical
spec:
  ports:
  - port: 9113
    name: metrics
  selector:
    app: nginx

